falco:
  image:
    repo: null
    tag: 0.40.0
  serviceAccount:
    name: falco-sa
  priority: null

driver:
  enabled: true
  kind: gvisor

affinity:
  nodeAffinity:
    requiredDuringSchedulingIgnoredDuringExecution:
      nodeSelectorTerms:
      - matchExpressions:
        - key: sandbox.gke.io/runtime
          operator: In
          values:
          - gvisor

tolerations:
  - effect: NoSchedule
    key: node-role.kubernetes.io/master
  - effect: NoSchedule
    key: sandbox.gke.io/runtime
    operator: Equal
    value: gvisor

falcoctl:
  artifact:
    install:
      enabled: true
    follow:
      enabled: true
  config:
    artifact:
      install:
        refs: [falco-rules:3]
      follow:
        refs: [falco-rules:3]

tty: false

metrics:
  image: null
  exporter:
    enabled: false
